from pathlib import Path
p=Path('SubtitleOverlayAndroid/app/src/main/java/com/sun/subtitleoverlay/overlay/OverlayService.kt')
s=p.read_text()
s=s.replace('        panel.addView(collapsibleSection("Playback", playbackControls))\n','')
s=s.replace('        panel.addView(collapsibleSection("Subtitle timing & size", subtitleControls))\n','')
s=s.replace('        panel.addView(collapsibleSection("Subtitle position", positionControls))\n','')
old='''        panel.addView(\n            collapsibleSection(\n                title = "Study mode",\n                content = studyControls,\n                initiallyExpanded = studyModeEnabled,\n                onExpandedChanged = ::setStudyMode,\n            )\n        )\n\n'''
new='''        val subtitlePage = LinearLayout(this).apply {\n            orientation = LinearLayout.VERTICAL\n            gravity = Gravity.CENTER\n            addView(subtitleControls)\n            addView(positionControls)\n        }\n        val tabRow = LinearLayout(this).apply {\n            orientation = LinearLayout.HORIZONTAL\n            gravity = Gravity.CENTER\n            setPadding(0, dp(6), 0, 0)\n        }\n        val tabContent = LinearLayout(this).apply {\n            orientation = LinearLayout.VERTICAL\n            gravity = Gravity.CENTER\n        }\n        lateinit var playbackTab: TextView\n        lateinit var subtitleTab: TextView\n        lateinit var studyTab: TextView\n        fun showTab(tab: String) {\n            playbackControls.visibility = if (tab == "playback") View.VISIBLE else View.GONE\n            subtitlePage.visibility = if (tab == "subtitle") View.VISIBLE else View.GONE\n            studyControls.visibility = if (tab == "study") View.VISIBLE else View.GONE\n            playbackTab.background = tabBackground(tab == "playback")\n            subtitleTab.background = tabBackground(tab == "subtitle")\n            studyTab.background = tabBackground(tab == "study")\n            playbackTab.setTextColor(if (tab == "playback") Color.WHITE else COLOR_MUTED_TEXT)\n            subtitleTab.setTextColor(if (tab == "subtitle") Color.WHITE else COLOR_MUTED_TEXT)\n            studyTab.setTextColor(if (tab == "study") Color.WHITE else COLOR_MUTED_TEXT)\n            setStudyMode(tab == "study")\n            tabContent.requestLayout()\n            controllerView?.requestLayout()\n        }\n        playbackTab = tabButton("Playback") { showTab("playback") }\n        subtitleTab = tabButton("Subtitle") { showTab("subtitle") }\n        studyTab = tabButton("Study") { showTab("study") }\n        tabRow.addView(playbackTab)\n        tabRow.addView(subtitleTab)\n        tabRow.addView(studyTab)\n        panel.addView(tabRow)\n        tabContent.addView(playbackControls)\n        tabContent.addView(subtitlePage)\n        tabContent.addView(studyControls)\n        panel.addView(tabContent)\n        showTab(if (studyModeEnabled) "study" else "playback")\n\n'''
if old not in s: raise SystemExit('study anchor missing')
s=s.replace(old,new,1)
anchor='    private fun chip(\n'
helper='''    private fun tabButton(label: String, action: () -> Unit) = TextView(this).apply {\n        text = label\n        textSize = 11f\n        typeface = Typeface.DEFAULT_BOLD\n        gravity = Gravity.CENTER\n        minWidth = dp(76)\n        minHeight = dp(32)\n        setPadding(dp(10), 0, dp(10), 0)\n        setTextColor(COLOR_MUTED_TEXT)\n        background = tabBackground(false)\n        isClickable = true\n        isFocusable = true\n        setOnClickListener { action() }\n        layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT).apply {\n            marginStart = dp(2)\n            marginEnd = dp(2)\n        }\n    }\n\n    private fun tabBackground(selected: Boolean) = roundedBackground(\n        if (selected) Color.argb(255, 105, 80, 164) else Color.argb(210, 42, 41, 48),\n        dp(9),\n        if (selected) 0xFF9B7FD1.toInt() else COLOR_BUTTON_BORDER,\n    )\n\n'''
if anchor not in s: raise SystemExit('chip anchor missing')
s=s.replace(anchor,helper+anchor,1)
p.write_text(s)
